# Preprocess

In [3]:
from sklearn.datasets import load_digits
digits = load_digits()
digits.data.shape

(1797, 64)

In [71]:
sample = digits.data[0]
sample = np.reshape(sample, [8, 8])
print(sample)
sample = np.where(sample > 7, 1, 0)
print(sample)
print(digits.target[0])

[[ 0.  0.  5. 13.  9.  1.  0.  0.]
 [ 0.  0. 13. 15. 10. 15.  5.  0.]
 [ 0.  3. 15.  2.  0. 11.  8.  0.]
 [ 0.  4. 12.  0.  0.  8.  8.  0.]
 [ 0.  5.  8.  0.  0.  9.  8.  0.]
 [ 0.  4. 11.  0.  1. 12.  7.  0.]
 [ 0.  2. 14.  5. 10. 12.  0.  0.]
 [ 0.  0.  6. 13. 10.  0.  0.  0.]]
[[0 0 0 1 1 0 0 0]
 [0 0 1 1 1 1 0 0]
 [0 0 1 0 0 1 1 0]
 [0 0 1 0 0 1 1 0]
 [0 0 1 0 0 1 1 0]
 [0 0 1 0 0 1 0 0]
 [0 0 1 0 1 1 0 0]
 [0 0 0 1 1 0 0 0]]
0


## Train and Test

In [65]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size=0.2, random_state=10)
print(x_train.shape, x_test.shape)

(1437, 64) (360, 64)


In [73]:
from sklearn.preprocessing import StandardScaler
from sklearn.svm import LinearSVC

ss = StandardScaler()
x_train = ss.fit_transform(x_train)
x_test = ss.transform(x_test)

lsvc = LinearSVC()
lsvc.fit(x_train, y_train)
y_predict = lsvc.predict(x_test)

In [76]:
from sklearn.metrics import classification_report
print('Accuracy:', lsvc.score(x_test, y_test))
print(classification_report(y_test, y_predict, target_names=digits.target_names.astype(str)))

Accuracy: 0.9472222222222222
             precision    recall  f1-score   support

          0       1.00      1.00      1.00        37
          1       0.89      0.94      0.91        34
          2       0.94      1.00      0.97        34
          3       0.97      0.97      0.97        40
          4       0.91      0.94      0.93        34
          5       0.94      0.94      0.94        32
          6       0.97      0.97      0.97        37
          7       1.00      0.97      0.99        40
          8       0.87      0.82      0.84        33
          9       0.95      0.90      0.92        39

avg / total       0.95      0.95      0.95       360

